### PR TITLE
Update vcpkg baseline for bugfixes

### PR DESCRIPTION
**Pull request by timkpaine**
- [x] grab https://github.com/microsoft/vcpkg/pull/39787

### CODE REVIEW

**Comment by timkpaine** [comment]
looks like `librdkafka` archives moved now 😢 
https://github.com/edenhill/librdkafka

**Comment by timkpaine** [comment]
xref: https://github.com/microsoft/vcpkg/issues/39828

**Comment by robambalu** [comment]
> xref: [microsoft/vcpkg#39828](https://github.com/microsoft/vcpkg/issues/39828)

how did we get around this

**Comment by timkpaine** [comment]
> how did we get around this

confluent restored the repos, they're looking into what happened that caused them to be deleted/hidden.

**Review by robambalu — APPROVED** [review]

**Pull request merged**
