### PR TITLE
Remove unused object_factory_registry. Fixes #377

### LINKED ISSUE #377: Remove csp.utils.object_factory_registry
**Is your feature request related to a problem? Please describe.**
This is no longer used and complicates the codebase

**Describe the solution you'd like**
Remove all references and usage of csp.utils.object_factory_registry

**Describe alternatives you've considered**
Leaving it in the codebase

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by ptomecek**
Fixes #377

### CODE REVIEW

**Review by robambalu — APPROVED** [review]

**Review by robambalu — COMMENTED** [review]
Looks like there are residual modules in utils/ that are no longer used, can we work through removing unused modules as well

**Review by robambalu — CHANGES_REQUESTED** [review]
Looks like there are residual modules in utils/ that are no longer used, can we work through removing unused modules as well

**Comment by ptomecek** [comment]
> Looks like there are residual modules in utils/ that are no longer used, can we work through removing unused modules as well

Yes. @robambalu Do you know what the status is of csp/utils/csp_watch_profile? It's a helper script with no references in the codebase, but might still be useful

**Comment by robambalu** [comment]
> > Looks like there are residual modules in utils/ that are no longer used, can we work through removing unused modules as well
> 
> Yes. @robambalu Do you know what the status is of csp/utils/csp_watch_profile? It's a helper script with no references in the codebase, but might still be useful

Yaeh we can probably leave that in there

**Pull request merged**
